### ISSUE TITLE
[PGsql] Index should be primary key , instead of Normal Index

### ISSUE THREAD

**Issue by yassinrais** [phalcon/migrations#112]
Table company
```php
 'indexes' => [
                    new Index('pk_company_id_0', ['id'], 'PRIMARY'),
                    new Index('unq_company_country_id', ['country_id', 'name'] ,'UNIQUE')
                ],
```

After runing migration 
![image](https://user-images.githubusercontent.com/25354731/115937611-b135a800-a498-11eb-956d-d13f49318ca6.png)

**Comment by yassinrais** [comment]
Oh , my bad it was 
```sql
PRIMARY KEY
```

Instead of 
```
PRIMARY
```

**Comment by yassinrais** [comment]
But the migration generator , does not put any option of indexing key 
he just let it empty like 

```php
 'indexes' => [
      new Index('pk_company_id_0', ['id'], ''),
      new Index('unq_company_country_id', ['country_id', 'name'] ,'')
  ],
```

**Comment by BeMySlaveDarlin** [comment]
I will check it soon and put a resolution.

**Comment by BeMySlaveDarlin** [comment]
First of all, pgsql adapter was hard locked for index definition creation. Using pg you should not have 'indexes' block. But you got that definition array just because your adapter in config file was Pascal case, so adapter check failed and indexes block was generated.

Made adapter check case insensitive and fixed indexes type definition.

Another point - in 'indexes' definition you wont have Primary index. That index is defined via Column definition by using option ```'primary' => true```.
